default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  host: localhost
  template: template0

development:
  <<: *default
  database: chromie_development

test: &test
  <<: *default
  database: chromie_test
  min_messages: WARNING
